#ifndef LAYERS_H
#define LAYERS_H

#include "main.h"     // For keycode constants and rowsCount/columnsCount

uint16_t layout0[rowsCount][columnsCount] = {
  {KEY_ESC,    KEY_F1,    KEY_F2,    KEY_F3,    KEY_F4,    KEY_F5,    KEY_F6,    KEY_F7,    KEY_F8,    KEY_F9,     KEY_F10,   KEY_F11,    KEY_F12,    KEY_DELETE  },
  {KEY_TILDE,  KEY_1,  KEY_2,  KEY_3,  KEY_4,  KEY_5,  KEY_6,  KEY_7,  KEY_8,  KEY_9,   KEY_0,  KEY_MINUS,  KEY_EQUAL,  KEY_PAGE_DOWN },
  {KEY_TAB,    KEY_Q,     KEY_W,     KEY_E,     KEY_R,     KEY_T,     KEY_Y,     KEY_U,     KEY_I,     KEY_O,      KEY_P,     KEY_LEFT_BRACE, KEY_RIGHT_BRACE, KEY_BACKSLASH},
  {KEY_CAPS_LOCK,   KEY_A,     KEY_S,     KEY_D,     KEY_F,     KEY_G,     KEY_H,     KEY_J,     KEY_K,     KEY_L,      KEY_SEMICOLON, KEY_QUOTE,  KEY_ENTER,  KEY_HOME },
  {KEY_LEFT_SHIFT,  KEY_Z,     KEY_X,     KEY_C,     KEY_V,     KEY_B,     KEY_N,     KEY_M,     KEY_COMMA, KEY_PERIOD, KEY_SLASH, KEY_RIGHT_SHIFT,  KEY_UP_ARROW,     KEY_END  },
  {KEY_LEFT_CTRL,  KEY_LEFT_GUI,  KEY_LEFT_ALT,  LAYER_1,  LAYER_2,  KEY_SPACE,   KEY_BACKSPACE, LAYER_3,  LAYER_4,  KEY_RIGHT_ALT,   KEY_RIGHT_CTRL, KEY_LEFT_ARROW,   KEY_DOWN_ARROW,   KEY_RIGHT_ARROW}
};

uint16_t layout1[rowsCount][columnsCount] = {
  {KEY_NULL,  KEY_F13,   KEY_F14,   KEY_F15,   KEY_F16,   KEY_F17,   KEY_F18,   KEY_F19,   KEY_F20,   KEY_F21,   KEY_F22,   KEY_F23,   KEY_F24,   KEY_NULL},
  {KEYPAD_ASTERIX, KEYPAD_SLASH,  KEYPAD_PLUS,  KEYPAD_MINUS,  KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEYPAD_7, KEYPAD_8,  KEYPAD_9,  KEY_QUOTE, KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEYPAD_4, KEYPAD_5,  KEYPAD_6,  KEY_DBLQUOTE,  KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_ENTER, KEY_NULL},
  {KEYPAD_1, KEYPAD_2,  KEYPAD_3,  KEY_ENTER, KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEYPAD_0, KEYPAD_0,  KEYPAD_PERIOD,  LAYER_1,  LAYER_2,  KEY_SPACE,   KEY_BACKSPACE, KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL}
};

uint16_t layout1_2[rowsCount][columnsCount] = {
  {KEY_ESC,    KEY_F13,   KEY_F14,   KEY_F15,   KEY_F16,   KEY_F17,   KEY_F18,   KEY_F19,   KEY_F20,   KEY_F21,   KEY_F22,   KEY_F23,   KEY_F24,   KEY_DELETE},
  {L_PARENTHESIS,   KEYPAD_ASTERIX,  KEYPAD_SLASH,  KEYPAD_PLUS,  KEYPAD_MINUS,  R_PARENTHESIS,  KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   NOT_EQUAL, KEY_EQUAL, KEY_NULL},
  {KEY_TAB,    KEYPAD_7,  KEYPAD_8,  KEYPAD_9,  KEY_CARAT, MACRO_SQUAREROOT,  KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEY_NULL,    KEYPAD_4,  KEYPAD_5,  KEYPAD_6,  KEY_EQUAL, KEY_DBLQUOTE,  KEY_NULL,   KEY_NULL,   LESS_EQUAL, GREAT_EQUAL, KEY_NULL,   KEY_NULL,   KEY_ENTER, KEY_NULL},
  {KEY_LEFT_SHIFT,  KEYPAD_1,  KEYPAD_2,  KEYPAD_3,  KEYPAD_ENTER,  KEY_NULL,   KEY_NULL,   KEY_NULL,   LEFT_CHEVRON, RIGHT_CHEVRON, KEY_NULL,   KEY_NULL,   KEY_UP_ARROW,    KEY_NUM_LOCK},
  {LAYER_1_2L,   KEYPAD_0,  KEYPAD_PERIOD,  KEYPAD_0,  LAYER_0,  KEY_SPACE,   KEY_BACKSPACE, LAYER_0,  KEY_NULL,   KEYPAD_PERIOD,  KEYPAD_0,  KEY_LEFT_ARROW,  KEY_DOWN_ARROW,  LAYER_1_2L}
};

uint16_t layout2[rowsCount][columnsCount] = {
  {KEY_ESC,    KEY_F13,   KEY_F14,   KEY_F15,   KEY_F16,   KEY_F17,   KEY_F18,   KEY_F19,   KEY_F20,   KEY_F21,   KEY_F22,   KEY_F23,   KEY_F24,   KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEY_ALT_TAB,   KEY_HOME,  KEY_UP_ARROW,    KEY_END,   KEY_PAGE_UP,  KEY_QUOTE, KEY_NULL,   UNDERSCORE,  KEY_NULL,   KEY_NULL,   KEY_PERCENT, KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEY_NULL,    KEY_LEFT_ARROW,  KEY_DOWN_ARROW,  KEY_RIGHT_ARROW, KEY_PAGE_DOWN,  KEY_DBLQUOTE,  KEY_MINUS, KEY_NULL,   KEY_NULL,   KEYPAD_PLUS,  KEY_NULL,   KEY_NULL,   KEY_ENTER, MOUSE_LCLICK},
  {KEY_LEFT_SHIFT,  KEY_NULL,   KEY_NULL,   KEY_NULL,   KEYPAD_ENTER,  KEY_BACKSLASH, AMPERSAND,  KEY_HASH,  LEFT_CHEVRON, RIGHT_CHEVRON, KEY_NULL,   KEY_NULL,   KEY_PAGE_UP,  KEY_NUM_LOCK},
  {LAYER_1_2L,   KEYPAD_0,  KEYPAD_PERIOD,  LAYER_1,  LAYER_2,  KEY_DELETE,   KEY_BACKSPACE, LAYER_3,  KEY_NULL,   KEY_RIGHT_ALT,  KEY_RIGHT_CTRL, KEY_BACKSPACE, KEY_PAGE_DOWN,  KEY_DELETE}
};

uint16_t layout2_3[rowsCount][columnsCount] = {
  {KEY_NULL,    KEY_F13,   KEY_F14,   KEY_F15,   KEY_F16,   KEY_F17,   KEY_F18,   KEY_F19,   KEY_F20,   KEY_F21,   KEY_F22,   KEY_F23,   KEY_F24,   KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEY_NULL,    QUESTION_MARK,  KEY_NULL,   EXCLMAMATION, KEY_ASTERISK,  KEY_NULL,   KEY_NULL,   UNDERSCORE,  KEY_NULL,   KEY_NULL,   KEY_PERCENT, KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEY_NULL,    KEY_AT,    KEY_SLASH, KEY_DOLLAR,  KEY_NULL,   KEY_DEGREES,  KEY_MINUS, KEY_NULL,   KEY_NULL,   KEYPAD_PLUS,  KEY_NULL,   KEY_NULL,   KEY_ENTER, KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_ASTERISK,  KEY_CARAT, KEY_NULL,   KEY_BACKSLASH, AMPERSAND,  KEY_HASH,  KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   LAYER_2,  KEY_SPACE,   KEY_BACKSPACE, LAYER_3,  KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL}
};

uint16_t layout3[rowsCount][columnsCount] = {
  {KEY_NULL,    KEY_F13,   KEY_F14,   KEY_F15,   KEY_F16,   KEY_F17,   KEY_F18,   KEY_F19,   KEY_F20,   KEY_F21,   KEY_F22,   KEY_F23,   KEY_F24,   KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   PLUS_MINUS,NOT_EQUAL, KEY_NULL},
  {KEY_NULL,    KEY_QUOTE, KEY_DBLQUOTE,  EXCLMAMATION, KEY_ASTERISK,  LEFT_CHEVRON, RIGHT_CHEVRON, UNDERSCORE,  KEY_NULL,   KEY_NULL,   KEY_PIPE,  KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   CURL_L_BRACE,KEY_LEFT_BRACE,L_PARENTHESIS,  R_PARENTHESIS,  KEY_RIGHT_BRACE,CURL_R_BRACE,KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_ENTER, KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   CMNTSTRT, KEY_BACKSLASH, AMPERSAND,  CMNTEND, LESS_EQUAL, GREAT_EQUAL, KEY_NULL,   KEY_NULL,   KEY_PAGE_UP,  KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   LAYER_2,  KEY_DELETE,   KEY_BACKSPACE, LAYER_3,  LAYER_4,  KEY_NULL,   KEY_NULL,   KEY_BACKSPACE, KEY_PAGE_DOWN,  KEY_DELETE}
};

uint16_t layout3_4[rowsCount][columnsCount] = {
  {KEY_NULL,    KEYSF13,  KEYSF14,  KEYSF15,  KEYSF16,  KEYSF17,  KEYSF18,  KEYSF19,  KEYSF20,  KEYSF21,  KEYSF22,  KEYSF23,  KEYSF24,  KEY_NULL},
  {LOOP_COUNT, KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEYPAD_ASTERIX,  KEYPAD_SLASH,  KEYPAD_PLUS,  KEYPAD_MINUS,  KEY_NULL,   KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   E_MACRON, KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEYPAD_7,  KEYPAD_8,  KEYPAD_9,  KEY_CARAT, KEY_NULL,   KEY_NULL},
  {KEY_NULL,    MACRO_AIMARENA,  KEY_NULL,   KEY_NULL,   KEY_NULL,   MACRO_GMAIL, KEY_NULL,   KEY_NULL,   KEYPAD_4,  KEYPAD_5,  KEYPAD_6,  KEY_NULL,   KEY_ENTER, KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   MACRO_LINEBREAK, KEY_NULL,   KEY_NULL,   KEYPAD_1,  KEYPAD_2,  KEYPAD_3,  KEY_NULL,   KEY_NULL,   KEY_NUM_LOCK},
  {KEY_NULL,    KEY_REBOOT,  KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_SPACE,   KEY_BACKSPACE, LAYER_3,  LAYER_4,  KEYPAD_0,  KEYPAD_PERIOD,  KEY_NULL,   KEY_NULL,   KEY_NULL}
};

uint16_t layout4[rowsCount][columnsCount] = {
  {KEY_CAPS_ESC,KEY_F13,   KEY_F14,   KEY_F15,   KEY_F16,   KEY_F17,   KEY_F18,   KEY_F19,   KEY_F20,   KEY_F21,   KEY_F22,   KEY_F23,   KEY_F24,   KEY_BACKSPACE},
  {LEDS_BR0,    LEDS_BR1,   LEDS_BR2,   LEDS_BR3,   LEDS_BR4,   LEDS_BR5,   LEDS_BR6,   LEDS_BR7,   LEDS_BR8,   LEDS_BR9,   LEDS_BR10,  KEY_NULL,   KEY_NULL,   LEDS_INC},
  {KEY_TAB,    KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_INSERT, KEY_NULL,   KEY_PAUSE, KEY_NULL,   KEY_NULL,   LEDS_DEC},
  {KEY_CAPS_SLASH,KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_SCROLL_LOCK, KEY_NULL,   KEY_NULL,   KEY_ENTER, KEY_NULL},
  {KEY_SET0,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_PRINTSCREEN,  KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_MEDIA_REWIND,  KEY_MEDIA_RECORD,   KEY_MEDIA_FAST_FORWARD},
  {KEY_RELEASE, KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_ALTL,  KEY_SPACE,   KEY_ALTR,  LAYER_3,  LAYER_4,  KEY_NULL,   KEY_NULL,   KEY_MEDIA_PREV_TRACK,  KEY_MEDIA_PLAY_PAUSE, KEY_MEDIA_NEXT_TRACK}
};


/*
uint16_t layoutNUL[rowsCount][columnsCount] = {
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL},
  {KEY_NULL,    KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL,   KEY_NULL}
};
*/

#endif
